
export const authConstants ={
    LOGIN_REQUEST: "USER_LOGIN_REQUEST",
    LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    LOGIN_FAILURE: "USER_LOGIN_FAILURE",

    CLEAR_LOGIN_ERRORS: "USER_CLEAR_LOGIN_ERRORS",

    REGISTER_REQUEST: "USER_REGISTER_REQUEST",
    REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    REGISTER_FAILURE: "USER_REGISTER_FAILURE",

    FORGOTPASSWORD_REQUEST: "USER_FORGOTPASSWORD_REQUEST",
    FORGOTPASSWORD_SUCCESS: "USER_FORGOTPASSWORD_SUCCESS",
    FORGOTPASSWORD_FAILURE: "USER_FORGOTPASSWORD_FAILURE",

    LOGOUT: "LOGOUT",

    GET_TOKEN : "USER_GET_TOKEN",
    SAVE_TOKEN : "USER_SAVE_TOKEN",
    DELETE_TOKEN : "USER_DELETE_TOKEN",



}